ax-llm/ax

- src/util/apicall.ts
Bug fix
issue: Azure OpenAI chat/completion call failed (#19 )
End point called: https://sqalia.openai.azure.com/openai/deployments/Sqalia4o/chat/completions/
(with an error 404 not found because api-version is required)
End point called: https://sqalia.openai.azure.com/openai/deployments/Sqalia4o/chat/completions/?api-version=2024-02-01
The issue is from the apiCall function who forgets the search parameters from baseURL
> fix: Azure OpenAI chat/completion call failed (#19)

- src/ai/cohere/api.ts
- src/ai/groq/api.ts
- src/examples/marketing.ts
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Updated Cohere reqValue to include input_type (it's now required since v3). I included a default value of 'classification'. All values appear to work, but some might be better suited for certain use cases.
- Updated Groq model to llama3-70b-8192 (llama2-70b-4096 was depreciated)
- Added a temporary fix to the marketing.py example, since messageGuidelines expects a string, not a string array. (it's just a hack to get it working)
**What is the current behavior?** (You can also link to an open issue here)
- Cohere embeddings and Groq won't work without the updates.
- Marketing.py throws an error.
> Updated Cohere, Groq, marketing.py

- src/dsp/index.ts
- src/dsp/loader.ts
- src/examples/summarize.ts
- This exports the data loader and allows the user to select the configuration for the dataset.
- This PR also fixes an issue with the summary example.
The optimization example is still failing, and there are still some issues with loading Hugging Face datasets where the answer isn't a string value. I think we need more optimization examples to show the true benefits of DSPy.
> Export hugging face data Loader and fix summarize example

- src/dsp/sig.ts
**What kind of change does this PR introduce?**
This pull request introduces a bug fix about the input fields type image.
**What is the current behavior?**
The current behavior is that when using the `AxGenerate::forward` function with an input parameter of type image, an error is thrown with the message: "Image type is not supported in output fields." This issue is described in more detail in the linked issue [#33](https://github.com/ax-llm/ax/issues/33).
**What is the new behavior (if this is a feature change)?**
With the changes introduced in this pull request, the `AxGenerate::forward` function will now properly accept input parameters of type image and process them without throwing any errors.
**Other information**:
I have tested these changes locally, and they resolve the issue …
> fix: input fields type image rejected #33

- package.json
- src/ax/package.json
Ava test timeout and "prepare" script changes
Ava tests fail
Ava test timeout increased and "prepare" script changed
> Ava test timeout and "prepare" script changes

- src/ax/ai/ollama/api.ts
Bug fix
The current implementation of the AxAIOllama class uses an incorrect API endpoint (/v1/embeddings) which results in a fetch failure when trying to generate embeddings.
The new behavior changes the endpoint to /api/embeddings, ensuring that the correct API URL is used.
This fix has been verified locally by testing the embedding generation endpoint from within the Docker container, ensuring the correct functionality.
The issue was identified in the node_modules/@ax-llm/ax/ai/ollama/api.js file.
Documentation for the correct API …
> corrected ollama embeddings api endpoint

- .cspell/project-words.txt
This PR adds AI-related terms (Codestral, Nemo, Codellama) to the spellcheck dictionary to resolve build failures due to spellcheck errors.
> Add terms to spellcheck dictionary

- src/ax/prompts/agent.ts
- src/examples/agent.ts
Currently, functions from agent instances are not properly bound to their respective agents. This causes this to be undefined when these functions are called, leading to unexpected behavior and potential errors.
Modify the function mapping process to bind agent functions to their respective instances. This ensures that when these functions are called, they have access to the correct this context.
```
Scientist receives the multi-part question
Splits it into individual questions
Sends each question to the Physics Researcher
Receives detailed bullet-point answers
Sends each detailed answer to the Science Summarizer
Receives concise summaries
Combines all information into a comprehensive, well-structured answer
```
> Fix: Bind agent functions to instances for correct 'this' context"

- src/ax/mem/memory.ts
- This PR is a typo correction
- BEFORE: when limit <= 0, throws a `last` error
- NOW: when limit <= 0, throws a `limit` error
> Fix: Typo in limit guard

- src/ax/ai/google-gemini/api.ts
Sometimes Gemini sends a STOP token here during normal processing. When this happens, `candidate.content.parts` is undefined, which causes the loop below to fail and crash generation with an exception:
```
Error summarizing message TypeError: candidate.content.parts is not iterable
at file:///Users/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@10.0.1/node_modules/@ax-llm/ax/ai/google-gemini/api.js:266:50
at Array.map (<anonymous>)
at AxAIGoogleGemini.generateChatResp (file:///Users/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@10.0.1/node_modules/@ax-llm/ax/ai/google-gemini/api.js:249:42)
at generateChatStreamResp (file:///Users/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@10.0.1/node_modules/@ax-llm/ax/ai/google-gemini/api.js:300:21)
at TypeTransformer.transformFn …
```
> Fix bug where Gemini STOP token causes crash

- src/ax/ai/google-gemini/api.ts
Improves error reporting in the case of a malformed function call
```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parts')
at file:///Users/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@10.0.9/node_modules/@ax-llm/ax/ai/google-gemini/api.js:274:34
at Array.map (<anonymous>)
at AxAIGoogleGemini.generateChatResp (file:///Users/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@10.0.9/node_modules/@ax-llm/ax/ai/google-gemini/api.js:257:42)
...
```
```sh
error: Uncaught (in promise) Error: Finish reason: …
```
> Handle MALFORMED_FUNCTION_CALL in google gemini api

- src/ax/dsp/prompt.ts
Bug fix
Currently, if a required field is type boolean, and the boolean value is false, isEmptyValue returns true and the signature fails validation.
Boolean false no longer fails the isEmptyValue check.
> Fix bug where boolean false is treated as empty

- src/ax/ai/balance.test.ts
- src/ax/ai/balance.ts
Adds a feature where the order in which AxBalancer cycles through services can be configured.
Currently AxBalancer always picks the cheapest service first.
The new behavior is that AxBalancer defaults to a "costComparator" that behaves identically to before. But now we can pass in a custom comparator that changes the service order / priority.
> Add configurable comparator for AxBalance service order

- src/ax/dsp/extract.test.ts
- src/ax/dsp/extract.ts
- src/ax/dsp/prompt.ts
- src/ax/dsp/util.test.ts
- src/ax/dsp/util.ts
Bug fix
Currently we render arrays as numbered lists, but parse LLM array output as JSON. This confuses the LLM in some cases.
The new behavior is that we render arrays as YAML, and more flexibly parse LLM arrays as JSON or YAML/Markdown.
> Render and parse YAML lists for array fields

- src/ax/ai/balance.test.ts
- src/ax/ai/balance.ts
Bug fix
Doc build fails because `getMetrics` call is missing in a couple places.
Doc build succeeds
> Add missing getMetrics call in AxBalancer and test mock

- src/ax/dsp/asserts.ts
Bug fix
Output field validation fails if an optional field has no value
Optional fields can have no value
> Fix: don't fail validation on missing optional field

- src/ax/ai/balance.test.ts
- src/ax/ai/balance.ts
Bug fix
Service comparators are not exported and hence cannot be used externally
Service comparators are exported along with the AxBalancer class
> Move service comparators inside AxBalancer class

- src/ax/ai/google-gemini/api.ts
- src/ax/ai/google-gemini/types.ts
Bug fix
Embedding requests to the Vertex API do not work:
```sh
➜  ax git:(main) ✗ npm run tsx src/examples/embedding.ts
> @ax-llm/ax-monorepo@10.0.38 tsx
> node --env-file=.env --import=tsx src/examples/embedding.ts
/Users/josh/Projects/ax/src/ax/util/apicall.ts:85
throw new Error(
^
Error: API Response Error: https://us-central1-aiplatform.googleapis.com/v1/projects/gsuite-importer-436622/locations/us-central1/publishers/google/models/text-embedding-004:batchEmbedContents
Error: API Request
Error: 404, Not Found
...
```
Embedding requests to the Vertex API work …
> Fix: embedding requests to Google Vertex API

- .cspell/project-words.txt
- package-lock.json
- src/ax/ai/anthropic/api.ts
- src/ax/ai/azure-openai/api.ts
- src/ax/ai/base.ts
- src/ax/ai/cohere/api.ts
- src/ax/ai/google-gemini/api.ts
- src/ax/ai/google-gemini/auth.ts
- src/ax/ai/huggingface/api.ts
- src/ax/ai/openai/api.ts
- src/ax/ai/reka/api.ts
- src/ax/package.json
Feature
Currently you must provide a long-lived apiKey key. This is not how the Vertex API is designed to work, though -- it's designed around an oauth2 / ADC flow with short-lived tokens.
Correctly implements oauth2 / ADC flow for authenticating to Vertex API
- **Testing**
Tested with examples. Everything works.
Config in `src/examples/chain-of-thought.ts`:
```TypeScript
const ai = new AxAI({
name: 'google-gemini',
projectId: '<PROJECT_ID>',
region: '<REGION>',
config: { model: AxAIGoogleGeminiModel.Gemini15Flash },
})
```
=>
```sh
$ npm run tsx …
```
> Add auth for Google Vertex API

- src/ax/dsp/generate.ts
Bug fix
Currently all calls to DeepSeek R1 on together.ai return empty results
DeepSeek R1 output returned properly
> Fix: deepseek r1 on together.ai returning empty result

- src/ax/dsp/generate.ts
Bug fix
Currently we occasionally see the following error:
```
TypeError: Cannot read properties of undefined (reading 'length')
at AxGen.processResponse (file:///home/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@11.0.5/node_modules/@ax-llm/ax/index.js:5820:21)
at AxGen.forwardCore (file:///home/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@11.0.5/node_modules/@ax-llm/ax/index.js:5711:24)
at eventLoopTick (ext:core/01_core.js:177:7)
at async AxGen._forward2 (file:///home/josh/Projects/bigb/api/node_modules/.deno/@ax-llm+ax@11.0.5/node_modules/@ax-llm/ax/index.js:5876:28)
...
```
- **What is the new behavior (if …
> fix: TypeError: Cannot read properties of undefined (reading 'length')

- src/ax/dsp/util.ts
Bug fix
Currently we cannot specify examples for "json" typed return values. It throws the following error:
```sh
Error: Validation failed: Expected 'answer' to be a json instead got 'string' ({ text: "Paris" })
at validateValue (/Users/josh/Projects/ax/src/ax/dsp/util.ts:134:11)
```
Examples for json-typed fields pass validation.
> Allow json examples to pass validation

- src/ax/dsp/prompt.ts
- Bug fix - incorrect prompt language
- From `./src/examples/extract.ts`:
- `Ticket Number: (Only include this number field is it's value is available)`
- `Customer Number: (Only include this number field is it's value is available)`
- From `./src/examples/extract.ts`:
- `Ticket Number: (Only include this number field if its value is available)`
- `Customer Number: (Only include this number field if its value is available)`
> chore: fix prompt language

- src/ax/ai/openai/api.ts
- src/ax/ai/openai/types.ts
Feature
OpenAI has deprecated the `max_tokens` param for a while now but this currently works with their `gpt-*` models.
However, this param is not supported in the reasoning models (`o1` and `o3` series)
https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens
By changing the param name from `max_tokens` to `max_completion_tokens` in the `openai` provider, users of the framework will be able to use the new reasoning models from OpenAI.
> feat: rename `max_tokens` to `max_completion_tokens` in `AxAIOpenAI`

- src/ax/index.ts
- **What kind of change does this PR introduce?** This is a bugfix. it adds evalUtils as an exported member of ax
- **What is the current behavior?** ([Issue 172](https://github.com/ax-llm/ax/issues/172))
- **What is the new behavior (if this is a feature change)?** This allows evalUtils to be imported and used 
> fix: evalUtils missing from exports in index.ts

- src/ax/ai/google-gemini/api.ts
Bug fix
Commit 8c9c8c4 broke support for Gemini Flash models 2.0 and before:
```
$ npm --env run tsx src/examples/chain-of-thought.ts
...
[cause]: [AxAIServiceStatusError: HTTP 400 - Bad Request
...
```
Inference fixed:
```
$ npm --env run tsx src/examples/chain-of-thought.ts
Question: What is the capital of France?
Assistant:
Reason: The context mentions that Paris is the capital of France.
Answer: ["Paris"]
{ answer: [ 'Paris' ] }
{
latency: {
chat: {
mean: 583.665417,
p95: 583.665417,
p99: 583.665417,
samples: [Array]
},
embed: { mean: 0, p95: 0, p99: 0, samples: …
```
> Fix: support for Gemini Flash <= 2.0

- src/ax/ai/google-gemini/api.ts
- src/ax/ai/openai/api.ts
**Description**
This PR fixes a TypeError that occurs when the `config` parameter is undefined in the `createChatReq` methods of AI implementations.
**Issue**
The `config` parameter can be undefined when called from certain contexts (e.g., MiPRO optimizer), causing crashes when accessing `config.thinkingTokenBudget` and `config.showThoughts`.
**Solution**
Added optional chaining (`?.`) to safely access these properties in:
- Google Gemini API implementation
- OpenAI API implementation
**Testing**
✅ Verified that MiPRO optimization now works without crashing
✅ Existing functionality remains unchanged when config is properly provided
**Files Changed**
- `src/ax/ai/google-gemini/api.ts`
- `src/ax/ai/openai/api.ts`
> fix: add null checks for config parameter in AI implementations

- src/ax/ai/google-gemini/api.ts
- src/ax/ai/openai/api.ts
**Description**
This PR fixes a bug where some metric functions in examples and documentation were returning boolean values instead of numbers, which violates the  type definition.
**Issue**
The  type is defined to return a , but some examples were returning  values:
This causes:
- Incorrect evaluation displays (showing "INCORRECT" for correct predictions)
- Potential issues in optimization algorithms that expect numeric scores
**Files Fixed**
-  - Changed  to return 
-  - Updated documentation example
**Testing**
✅ Examples now correctly return numeric scores
✅ Type definitions are satisfied
> fix: metric functions should return numbers, not booleans

- src/ax/ai/mistral/api.ts
- src/ax/index.ts
Bug fix
When using the Mistral provider, the parameters max_completion_token and stream_options are passed but are not supported by the provider’s API, causing potential runtime issues or unexpected behavior. Additionally, the topP parameter may be undefined or not set, leading to inconsistencies in completion quality.
This PR ensures max_completion_token and stream_options are no longer included in the request when using the Mistral provider. It also sets a default value of topP = 1 when not explicitly provided, aligning with typical usage expectations and …
> fix(mistral): remove unsupported params and fix image compatibility

- .cspell/project-words.txt
- src/ax/ai/google-gemini/api.ts
Bug fix
Currently inference fails with 404 - Not Found for any model in the "global" region.
```
$ npm --env run tsx src/examples/chain-of-thought.ts
... snip ....
responseBody: {
httpStatus: 404,
httpStatusText: 'Not Found',
... snip ...
```
Inference works for "global" region.
```
$ npm --env run tsx src/examples/chain-of-thought.ts
Assistant:
Reason: The user is asking for the capital of France. I need to find the sentence in the context that explicitly states this information. The first sentence states "Paris is the capital and most populous city of France." The …
```
> Use correct TLD for Google Vertex "global" region

- src/ax/dsp/processResponse.ts
BugFix: streaming models used to append one `modelUsage` per chunk streamed instead of per-call. This lead to severly overinflated token usage counts.
Resolves https://github.com/ax-llm/ax/issues/199
Only one modelUsage count per streaming response.
How can I test this properly?
> fix: only count last modelUsage chunk for streaming models

- src/ax/dsp/functions.ts
- src/ax/dsp/generate.ts
- src/ax/dsp/jsonSchemaToSignature.ts
- src/ax/dsp/sig.ts
- src/ax/dsp/signatureToolCalling.test.ts
- src/ax/dsp/signatureToolCalling.ts
- src/ax/dsp/signatureToolCallingDisabled.test.ts
- src/ax/dsp/signatureToolDotNotation.test.ts
- src/ax/dsp/signatureToolIntegration.test.ts
- src/ax/dsp/signatureToolRouter.ts
- src/ax/dsp/toolSchemaConverter.ts
- src/ax/dsp/types.ts
- src/examples/signature-tool-calling.ts
- **What kind of change does this PR introduce?** Feature - adds signature tool calling capability for LLMs without native tool support
- **What is the current behavior?** Models without native tool calling APIs cannot leverage Ax's tool execution capabilities
- **What is the new behavior (if this is a feature change)?** 
- Adds  flag to enable tool execution via signature fields
- Tool schemas automatically inject as optional signature fields
- LLM populates tool fields → Ax executes tools → returns combined results
- Works with any model regardless of native tool support
- Zero breaking changes, opt-in via flag
- Comprehensive test suite with 12 passing tests
- Working example provided in 
- Type-safe implementation with full TypeScript support
- Compatible with …
> feat: add signature tool calling for non-native tool support

- src/ax/dsp/optimizers/gepa.ts
- src/examples/gepa-train-inference.ts
This PR improves GEPA save/load ergonomics:
- Save training instructions in optimizedProgram so applyOptimization restores them (src/ax/dsp/optimizers/gepa.ts).
- Add runnable GEPA train+inference example that saves to JSON and reloads (src/examples/gepa-train-inference.ts).
Notes:
- GEPA doesn’t optimize demos; examples are persisted for convenience. Demos remain [].
- Follow-up could add the same optimizedProgram behavior to GEPA-Flow and an option to persist validationExamples.
> GEPA: enable optimizedProgram interface to mirror MiPRO

- docs/OPTIMIZE.md
- src/ax/dsp/common_types.ts
- src/docs/src/content/docs/optimize.md
- src/examples/gepa-flow.ts
- src/examples/gepa-quality-vs-speed-optimization.ts
- src/examples/gepa-train-inference.ts
- src/examples/gepa.ts
- **What kind of change does this PR introduce?** Type fix enhancement to support GEPA feedback mechanisms
- **What is the current behavior?** Users cannot provide feedback to the reflection stage in GEPA optimization, which was a critical missing feature mentioned in the paper and highlighted by community feedback. The tools exist today, but it's not discoverable nor obvious how to use.
- **What is the new behavior (if this is a feature change)?** AxCompileOptions now exposes typed hooks for GEPA feedback:
- \`validationExamples\`: Separate validation dataset for evaluation
- \`feedbackExamples\`: Dedicated feedback dataset for reviewer input  
- \`feedbackFn\`: Callback function to gather reviewer notes on evaluated tuples
These hooks enable external feedback to influence instruction …
> fix: add GEPA feedback type hooks to AxCompileOptions
