- package-lock.json
- src/proxy/parsers.ts
bug fix, chore
Anthropic proxy endpoint was wrong, leading to an error in response
It uses the correct anthropic api endpoint, so it works as expected
the updated package-lock.json comes from running `npm install`, looks like that needed updating anyways (such as the version number)
> fix: anthropic proxy endpoint

- README.md
docs update
Lack of info how to install it
Info how to install it added to readme
> docs: improve docs, add install info

- src/examples/lares-smart-home.ts
This PR implements the Lares smart home assistant using llmclient to demonstrate the ease of building AI agents with emergent behavior. The implementation showcases a simulation of a smart home assistant that exhibits problem-solving abilities despite its simplicity.
For more details on emergent behavior in AI agents, see this reference: https://interconnected.org/more/2024/lares/
Key Features
Agent Implementation: Utilizes llmclient to build a simple AI agent that controls a smart home environment.
Smart Home Simulation: The agent interacts with a simulated smart home, including turning lights on and off, moving a robot between rooms, and looking for a dog.
Emergent Behavior: Demonstrates how the agent can autonomously make decisions based on the state of the environment.
> Implement Lares Smart Home Assistant Using llmclient

- src/dsp/loader.ts
- src/examples/qna-tune.ts
- src/examples/qna-use-tuned.ts
Additional work done:
-Update qna-tune.ts to use a a simple query answer. Otherwise emScore returns no positive results.
- Update qna-use-tuned.ts to use the tuned model.
> Remove casting to a string value in the loader

- .github/workflows/static.yml
- package-lock.json
- package.json
- src/ax/.release-it.json
- src/ax/package.json
> Test improvements - Fix Ava runs on CI 

- .release-it.json
- package.json
- src/ax/.release-it.json
Release process improvements - correctly mark every version
> Release process improvements

- package.json
- src/ax/package.json
- src/examples/package.json
Fix release files array to get all the needed files
Not all files were in NPM package
> fix: release files

- scripts/postbuild.js
Fixing issue https://github.com/ax-llm/ax/issues/47
Node.js plain JS imports are not always working
> Fix node imports

- .release-it.json
- package-lock.json
- package.json
Auto-add release changelog after the release
When releasing, Changelog file is not updated
Auto-add release changelog after the release
> Auto-add release changelog after the release

- src/ax/ai/ollama/api.ts
- src/ax/ai/ollama/info.ts
- src/ax/ai/ollama/types.ts
* **What kind of change does this PR introduce?** 
This PR enhances the Ollama API integration with better error handling and fixes issues with streaming responses.
* **What is the current behavior?** 
The current implementation struggles with parsing streamed responses, leading to frequent JSON parsing errors. It also lacks robust error handling and debugging capabilities.
* **What is the new behavior?** 
The updated implementation:
- Correctly handles chunked responses in the stream, resolving JSON parsing issues
- Improves error handling and adds detailed logging for easier troubleshooting
- Enhances the embedding functionality to use 'prompt' instead of 'input' to align with Ollama's API
- Adds debug options for more visibility into the API interactions
* **Other information**:
This …
> Enhance Ollama API integration with improved error handling and streaming

- README.md
- src/docs/src/content/docs/guides/dsp.md
- src/docs/src/content/docs/guides/functions-1.md
- src/docs/src/content/docs/guides/functions-2.md
- src/docs/src/content/docs/guides/production-deploy.md
- src/docs/src/content/docs/start/about.md
- src/docs/src/content/docs/start/llms.md
- src/docs/src/content/docs/start/quick.md
This is a super cool package. I read through the docs and spotted some grammatical issues so I fixed them. Additionally, phrases that might be hard to read due to them being long or clunky have been broken up or reworded whilst retaining the meaning (minor changes).
Enjoy!
> chore(docs): fix grammar

- README.md
- package-lock.json
- package.json
- src/ai-sdk-provider/index.ts
- src/ax/ai/openai/api.ts
- src/ax/ai/openai/types.ts
- src/ax/ai/types.ts
- src/ax/dsp/parser.ts
- src/ax/dsp/program.ts
- src/ax/dsp/prompt.ts
- src/ax/dsp/sig.ts
- src/ax/dsp/util.ts
- src/docs/src/content/docs/start/quick.md
https://platform.openai.com/docs/guides/audio?audio-generation-quickstart-example=audio-in
audio type is unknown
we can send audio for input parameters
> feat: add input audio type compatibility

- src/docs/src/content/docs/guides/dsp.md
> Fix bullet typo in dsp.md

- README.md
docs update:
The phrase "LLMs Powered Agents" has a structural problem.
A more natural phrasing would include a hyphen to clarify the relationship: "LLM-Powered Agents."
NA
NA
NA
> The phrase "LLMs Powered Agents" has a structural problem.

- src/ax/ai/groq/api.ts
Bug fix
npm ci failure
npm ci succeeds
> Fix: ci failure

- src/ax/ai/balance.ts
Feature
No logging when balancer fails over to a different service
Added logging for this case
> Add logging for balancer failover

- src/ax/ai/google-gemini/types.ts
Feature
text-model-005 unavailable
text-model-005 available
> Add support for Google text-embedding-005 model

- src/ax/ai/balance.ts
- src/ax/ai/google-vertex/auth.ts
Bug fix
Originating exception gets swallowed in AxBalancer
Exception is logged
> fix: don't swallow error in AxBalancer

- src/ax/ai/google-vertex/auth.ts
Bug fix
We were manually managing the cacheing and lifecycle of auth tokens
Google auth lib does this instead
> fix: allow google auth lib to manage token lifecycle

- src/ax/ai/google-gemini/api.ts
Feature
Currently Vertex endpoints for custom models (like fine-tunes) are not supported
Adds support for custom endpoints
> Add support for Vertex API custom model endpoints

- src/docs/src/content/docs/01-start/03-llms.md
> chore: update ollama docs

- src/ax/util/apicall.ts
https://github.com/ax-llm/ax/issues/180
https://github.com/ax-llm/ax/issues/180
> fix: Azure OpenAI chat/completion call failed #180

- package.json
- src/aisdk/package.json
- src/ax/README.md
- src/ax/package.json
- src/examples/package.json
- src/tools/package.json
Homepage link updated, root README.md copied to src/ax
- **What kind of change does this PR introduce?**
Updates homepage link on npm page and adds a README
Helps with #324 
😢 Before (404): https://github.com/@ax-llm/ax#readme 404's
✅ After (works): https://github.com/ax-llm/ax#readme
> Update package.json homepage for npm

- src/ax/ai/cohere/api.ts
- src/ax/ai/deepseek/api.ts
- src/ax/ai/ollama/api.ts
- src/ax/mcp/oauth/pkce.ts
- src/docs/src/lib/autocomplete.ts
Docs
#347 
Started with some reference docs and will be moving up to more high level soon enough
> Added Reference documentation - batch 1
